set zarr maximum chunk size to 1Gb
Avoids this exception from zarr:
  ValueError: Codec does not support buffers of > 2147483647 bytes

Letting zarr choose the chunk size results in lots of small files,
so we use one single chunk unless its size exceeds 1Gb.